language: rust

rust:
  - nightly

env:
  global:
    - CC=gcc-4.8
    - CXX=g++-4.8

# install Cap'n Proto.
install:
    - git clone https://github.com/kentonv/capnproto.git
    - cd capnproto/c++
    - git checkout release-0.5.3
    - ./setup-autotools.sh
    - autoreconf -i
    - ./configure --disable-shared
    - make -j5
    - export PATH="$PATH:$(pwd)"
    - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(pwd)"
    -  cd ../..

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
        # Needed for building Cap'n Proto.
      - gcc-4.8
      - g++-4.8

script:
  - cargo build -v
  - env RUST_BACKTRACE=1 cargo test -v;
